### ISSUE TITLE
ISSUE: does not work well with DeArrow extension on opera GX on windows 10

### ISSUE THREAD

**Issue by codeman3000** [MagicJinn/MrBeastify-Youtube#47] opened 2023-11-05 05:55 UTC
This extension does not work with DeArrow generated thumbnails on opera gx browser

To replicate: 

1. Use opera GX (i do not know if this issue is reproducible on other browsers, it may happen on chrome)
2. install Dearrow: https://chrome.google.com/webstore/detail/dearrow-better-titles-and/enamippconapkdmgfgjchkhakpfinmaj
3. Refresh youtube and thumbails do not include Mr. Beast

**Comment by JxxIT** [comment] 2023-11-05 07:46
Opera GX, is chromium based. The extension should not run different from chrome, so it's a duplicate of #41

**Comment by MagicJinn** [comment] 2023-11-05 19:04
DeArrow has been known to be incompatible with this extension, which I should probably put on the extension page itself. I guess that an extension created to make videos more clickbaity mixed with an extension to de-clickbait youtube wouldn't work together.

**Closed by MagicJinn** 2023-11-05 19:04 UTC
Labels: duplicate
